# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: PyPI Release Actions

on:
  workflow_dispatch:

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Run PyPI Release CI workflow
      uses: adafruit/workflows-circuitpython-libs/release-pypi@main
      with:
        pypi-username: __token__
        pypi-password: ${{ secrets.PYPI_API_TOKEN }}
